// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WeWrite/WeWriteProtocolBuffer.proto

package edu.umich.imlc.mydesk.app.wewrite;

public final class WeWriteProtocolBuffer {
  private WeWriteProtocolBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WeWriteFile_PBOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string file_i_d = 1;
    boolean hasFileID();
    String getFileID();
    
    // optional string file_name = 2;
    boolean hasFileName();
    String getFileName();
    
    // optional string text_data = 3;
    boolean hasTextData();
    String getTextData();
    
    // optional string file_format_version = 4;
    boolean hasFileFormatVersion();
    String getFileFormatVersion();
  }
  public static final class WeWriteFile_PB extends
      com.google.protobuf.GeneratedMessage
      implements WeWriteFile_PBOrBuilder {
    // Use WeWriteFile_PB.newBuilder() to construct.
    private WeWriteFile_PB(Builder builder) {
      super(builder);
    }
    private WeWriteFile_PB(boolean noInit) {}
    
    private static final WeWriteFile_PB defaultInstance;
    public static WeWriteFile_PB getDefaultInstance() {
      return defaultInstance;
    }
    
    public WeWriteFile_PB getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.internal_static_WeWriteFile_PB_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.internal_static_WeWriteFile_PB_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string file_i_d = 1;
    public static final int FILE_I_D_FIELD_NUMBER = 1;
    private java.lang.Object fileID_;
    public boolean hasFileID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getFileID() {
      java.lang.Object ref = fileID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fileID_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFileIDBytes() {
      java.lang.Object ref = fileID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fileID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string file_name = 2;
    public static final int FILE_NAME_FIELD_NUMBER = 2;
    private java.lang.Object fileName_;
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fileName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string text_data = 3;
    public static final int TEXT_DATA_FIELD_NUMBER = 3;
    private java.lang.Object textData_;
    public boolean hasTextData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getTextData() {
      java.lang.Object ref = textData_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          textData_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextDataBytes() {
      java.lang.Object ref = textData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        textData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string file_format_version = 4;
    public static final int FILE_FORMAT_VERSION_FIELD_NUMBER = 4;
    private java.lang.Object fileFormatVersion_;
    public boolean hasFileFormatVersion() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getFileFormatVersion() {
      java.lang.Object ref = fileFormatVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fileFormatVersion_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFileFormatVersionBytes() {
      java.lang.Object ref = fileFormatVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fileFormatVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      fileID_ = "";
      fileName_ = "";
      textData_ = "";
      fileFormatVersion_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFileIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTextDataBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getFileFormatVersionBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFileIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTextDataBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getFileFormatVersionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.internal_static_WeWriteFile_PB_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.internal_static_WeWriteFile_PB_fieldAccessorTable;
      }
      
      // Construct using edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        fileID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        textData_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        fileFormatVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB.getDescriptor();
      }
      
      public edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB getDefaultInstanceForType() {
        return edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB.getDefaultInstance();
      }
      
      public edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB build() {
        edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB buildPartial() {
        edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB result = new edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fileID_ = fileID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fileName_ = fileName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.textData_ = textData_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fileFormatVersion_ = fileFormatVersion_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB) {
          return mergeFrom((edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB other) {
        if (other == edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB.getDefaultInstance()) return this;
        if (other.hasFileID()) {
          setFileID(other.getFileID());
        }
        if (other.hasFileName()) {
          setFileName(other.getFileName());
        }
        if (other.hasTextData()) {
          setTextData(other.getTextData());
        }
        if (other.hasFileFormatVersion()) {
          setFileFormatVersion(other.getFileFormatVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fileID_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              fileName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              textData_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              fileFormatVersion_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string file_i_d = 1;
      private java.lang.Object fileID_ = "";
      public boolean hasFileID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFileID() {
        java.lang.Object ref = fileID_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fileID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFileID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileID_ = value;
        onChanged();
        return this;
      }
      public Builder clearFileID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fileID_ = getDefaultInstance().getFileID();
        onChanged();
        return this;
      }
      void setFileID(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        fileID_ = value;
        onChanged();
      }
      
      // optional string file_name = 2;
      private java.lang.Object fileName_ = "";
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFileName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fileName_ = value;
        onChanged();
        return this;
      }
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      void setFileName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        fileName_ = value;
        onChanged();
      }
      
      // optional string text_data = 3;
      private java.lang.Object textData_ = "";
      public boolean hasTextData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getTextData() {
        java.lang.Object ref = textData_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          textData_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTextData(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        textData_ = value;
        onChanged();
        return this;
      }
      public Builder clearTextData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        textData_ = getDefaultInstance().getTextData();
        onChanged();
        return this;
      }
      void setTextData(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        textData_ = value;
        onChanged();
      }
      
      // optional string file_format_version = 4;
      private java.lang.Object fileFormatVersion_ = "";
      public boolean hasFileFormatVersion() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getFileFormatVersion() {
        java.lang.Object ref = fileFormatVersion_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fileFormatVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFileFormatVersion(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fileFormatVersion_ = value;
        onChanged();
        return this;
      }
      public Builder clearFileFormatVersion() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fileFormatVersion_ = getDefaultInstance().getFileFormatVersion();
        onChanged();
        return this;
      }
      void setFileFormatVersion(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        fileFormatVersion_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:WeWriteFile_PB)
    }
    
    static {
      defaultInstance = new WeWriteFile_PB(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:WeWriteFile_PB)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_WeWriteFile_PB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_WeWriteFile_PB_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#WeWrite/WeWriteProtocolBuffer.proto\"e\n" +
      "\016WeWriteFile_PB\022\020\n\010file_i_d\030\001 \001(\t\022\021\n\tfil" +
      "e_name\030\002 \001(\t\022\021\n\ttext_data\030\003 \001(\t\022\033\n\023file_" +
      "format_version\030\004 \001(\tB#\n!edu.umich.imlc.m" +
      "ydesk.app.wewrite"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_WeWriteFile_PB_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_WeWriteFile_PB_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_WeWriteFile_PB_descriptor,
              new java.lang.String[] { "FileID", "FileName", "TextData", "FileFormatVersion", },
              edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB.class,
              edu.umich.imlc.mydesk.app.wewrite.WeWriteProtocolBuffer.WeWriteFile_PB.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
