// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WeTimeline/WeTimelineProtocolBuffer.proto

package edu.umich.imlc.mydesk.app.wetimeline;

public final class WeTimelineProtocolBuffer {
  private WeTimelineProtocolBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WeTimelineEvent_PBOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .WeTimelineEvent_PB.actionType action_type = 1;
    boolean hasActionType();
    edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.actionType getActionType();
    
    // optional .WeTimelineEvent_PB.eventType event_type = 2;
    boolean hasEventType();
    edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.eventType getEventType();
    
    // optional .TimelineEvent_PB timeline_event = 3;
    boolean hasTimelineEvent();
    edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB getTimelineEvent();
    edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder getTimelineEventOrBuilder();
    
    // optional string user_id = 4;
    boolean hasUserId();
    String getUserId();
  }
  public static final class WeTimelineEvent_PB extends
      com.google.protobuf.GeneratedMessage
      implements WeTimelineEvent_PBOrBuilder {
    // Use WeTimelineEvent_PB.newBuilder() to construct.
    private WeTimelineEvent_PB(Builder builder) {
      super(builder);
    }
    private WeTimelineEvent_PB(boolean noInit) {}
    
    private static final WeTimelineEvent_PB defaultInstance;
    public static WeTimelineEvent_PB getDefaultInstance() {
      return defaultInstance;
    }
    
    public WeTimelineEvent_PB getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.internal_static_WeTimelineEvent_PB_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.internal_static_WeTimelineEvent_PB_fieldAccessorTable;
    }
    
    public enum actionType
        implements com.google.protobuf.ProtocolMessageEnum {
      NEW_ACTION(0, 1),
      UNDO_ACTION(1, 2),
      REDO_ACTION(2, 3),
      ;
      
      public static final int NEW_ACTION_VALUE = 1;
      public static final int UNDO_ACTION_VALUE = 2;
      public static final int REDO_ACTION_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static actionType valueOf(int value) {
        switch (value) {
          case 1: return NEW_ACTION;
          case 2: return UNDO_ACTION;
          case 3: return REDO_ACTION;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<actionType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<actionType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<actionType>() {
              public actionType findValueByNumber(int number) {
                return actionType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final actionType[] VALUES = {
        NEW_ACTION, UNDO_ACTION, REDO_ACTION, 
      };
      
      public static actionType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private actionType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:WeTimelineEvent_PB.actionType)
    }
    
    public enum eventType
        implements com.google.protobuf.ProtocolMessageEnum {
      ADD_ITEM(0, 1),
      EDIT_ITEM(1, 2),
      DELETE_ITEM(2, 3),
      ;
      
      public static final int ADD_ITEM_VALUE = 1;
      public static final int EDIT_ITEM_VALUE = 2;
      public static final int DELETE_ITEM_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static eventType valueOf(int value) {
        switch (value) {
          case 1: return ADD_ITEM;
          case 2: return EDIT_ITEM;
          case 3: return DELETE_ITEM;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<eventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<eventType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<eventType>() {
              public eventType findValueByNumber(int number) {
                return eventType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final eventType[] VALUES = {
        ADD_ITEM, EDIT_ITEM, DELETE_ITEM, 
      };
      
      public static eventType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private eventType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:WeTimelineEvent_PB.eventType)
    }
    
    private int bitField0_;
    // optional .WeTimelineEvent_PB.actionType action_type = 1;
    public static final int ACTION_TYPE_FIELD_NUMBER = 1;
    private edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.actionType actionType_;
    public boolean hasActionType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.actionType getActionType() {
      return actionType_;
    }
    
    // optional .WeTimelineEvent_PB.eventType event_type = 2;
    public static final int EVENT_TYPE_FIELD_NUMBER = 2;
    private edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.eventType eventType_;
    public boolean hasEventType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.eventType getEventType() {
      return eventType_;
    }
    
    // optional .TimelineEvent_PB timeline_event = 3;
    public static final int TIMELINE_EVENT_FIELD_NUMBER = 3;
    private edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB timelineEvent_;
    public boolean hasTimelineEvent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB getTimelineEvent() {
      return timelineEvent_;
    }
    public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder getTimelineEventOrBuilder() {
      return timelineEvent_;
    }
    
    // optional string user_id = 4;
    public static final int USER_ID_FIELD_NUMBER = 4;
    private java.lang.Object userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      actionType_ = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.actionType.NEW_ACTION;
      eventType_ = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.eventType.ADD_ITEM;
      timelineEvent_ = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.getDefaultInstance();
      userId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, actionType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, eventType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, timelineEvent_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUserIdBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, actionType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, eventType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, timelineEvent_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUserIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.internal_static_WeTimelineEvent_PB_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.internal_static_WeTimelineEvent_PB_fieldAccessorTable;
      }
      
      // Construct using edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTimelineEventFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        actionType_ = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.actionType.NEW_ACTION;
        bitField0_ = (bitField0_ & ~0x00000001);
        eventType_ = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.eventType.ADD_ITEM;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (timelineEventBuilder_ == null) {
          timelineEvent_ = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.getDefaultInstance();
        } else {
          timelineEventBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.getDescriptor();
      }
      
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB getDefaultInstanceForType() {
        return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.getDefaultInstance();
      }
      
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB build() {
        edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB buildPartial() {
        edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB result = new edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.actionType_ = actionType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.eventType_ = eventType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (timelineEventBuilder_ == null) {
          result.timelineEvent_ = timelineEvent_;
        } else {
          result.timelineEvent_ = timelineEventBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userId_ = userId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB) {
          return mergeFrom((edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB other) {
        if (other == edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.getDefaultInstance()) return this;
        if (other.hasActionType()) {
          setActionType(other.getActionType());
        }
        if (other.hasEventType()) {
          setEventType(other.getEventType());
        }
        if (other.hasTimelineEvent()) {
          mergeTimelineEvent(other.getTimelineEvent());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.actionType value = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.actionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                actionType_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.eventType value = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.eventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                eventType_ = value;
              }
              break;
            }
            case 26: {
              edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder subBuilder = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.newBuilder();
              if (hasTimelineEvent()) {
                subBuilder.mergeFrom(getTimelineEvent());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTimelineEvent(subBuilder.buildPartial());
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              userId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .WeTimelineEvent_PB.actionType action_type = 1;
      private edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.actionType actionType_ = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.actionType.NEW_ACTION;
      public boolean hasActionType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.actionType getActionType() {
        return actionType_;
      }
      public Builder setActionType(edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.actionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        actionType_ = value;
        onChanged();
        return this;
      }
      public Builder clearActionType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        actionType_ = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.actionType.NEW_ACTION;
        onChanged();
        return this;
      }
      
      // optional .WeTimelineEvent_PB.eventType event_type = 2;
      private edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.eventType eventType_ = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.eventType.ADD_ITEM;
      public boolean hasEventType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.eventType getEventType() {
        return eventType_;
      }
      public Builder setEventType(edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.eventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        eventType_ = value;
        onChanged();
        return this;
      }
      public Builder clearEventType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        eventType_ = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.eventType.ADD_ITEM;
        onChanged();
        return this;
      }
      
      // optional .TimelineEvent_PB timeline_event = 3;
      private edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB timelineEvent_ = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder> timelineEventBuilder_;
      public boolean hasTimelineEvent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB getTimelineEvent() {
        if (timelineEventBuilder_ == null) {
          return timelineEvent_;
        } else {
          return timelineEventBuilder_.getMessage();
        }
      }
      public Builder setTimelineEvent(edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB value) {
        if (timelineEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timelineEvent_ = value;
          onChanged();
        } else {
          timelineEventBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setTimelineEvent(
          edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder builderForValue) {
        if (timelineEventBuilder_ == null) {
          timelineEvent_ = builderForValue.build();
          onChanged();
        } else {
          timelineEventBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeTimelineEvent(edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB value) {
        if (timelineEventBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              timelineEvent_ != edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.getDefaultInstance()) {
            timelineEvent_ =
              edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.newBuilder(timelineEvent_).mergeFrom(value).buildPartial();
          } else {
            timelineEvent_ = value;
          }
          onChanged();
        } else {
          timelineEventBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearTimelineEvent() {
        if (timelineEventBuilder_ == null) {
          timelineEvent_ = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.getDefaultInstance();
          onChanged();
        } else {
          timelineEventBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder getTimelineEventBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTimelineEventFieldBuilder().getBuilder();
      }
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder getTimelineEventOrBuilder() {
        if (timelineEventBuilder_ != null) {
          return timelineEventBuilder_.getMessageOrBuilder();
        } else {
          return timelineEvent_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder> 
          getTimelineEventFieldBuilder() {
        if (timelineEventBuilder_ == null) {
          timelineEventBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder>(
                  timelineEvent_,
                  getParentForChildren(),
                  isClean());
          timelineEvent_ = null;
        }
        return timelineEventBuilder_;
      }
      
      // optional string user_id = 4;
      private java.lang.Object userId_ = "";
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      void setUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        userId_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:WeTimelineEvent_PB)
    }
    
    static {
      defaultInstance = new WeTimelineEvent_PB(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:WeTimelineEvent_PB)
  }
  
  public interface WeTimelineFile_PBOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string file_name = 1;
    boolean hasFileName();
    String getFileName();
    
    // repeated .TimelineEvent_PB timeline_event = 2;
    java.util.List<edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB> 
        getTimelineEventList();
    edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB getTimelineEvent(int index);
    int getTimelineEventCount();
    java.util.List<? extends edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder> 
        getTimelineEventOrBuilderList();
    edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder getTimelineEventOrBuilder(
        int index);
    
    // optional string file_type = 3;
    boolean hasFileType();
    String getFileType();
  }
  public static final class WeTimelineFile_PB extends
      com.google.protobuf.GeneratedMessage
      implements WeTimelineFile_PBOrBuilder {
    // Use WeTimelineFile_PB.newBuilder() to construct.
    private WeTimelineFile_PB(Builder builder) {
      super(builder);
    }
    private WeTimelineFile_PB(boolean noInit) {}
    
    private static final WeTimelineFile_PB defaultInstance;
    public static WeTimelineFile_PB getDefaultInstance() {
      return defaultInstance;
    }
    
    public WeTimelineFile_PB getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.internal_static_WeTimelineFile_PB_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.internal_static_WeTimelineFile_PB_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string file_name = 1;
    public static final int FILE_NAME_FIELD_NUMBER = 1;
    private java.lang.Object fileName_;
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fileName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .TimelineEvent_PB timeline_event = 2;
    public static final int TIMELINE_EVENT_FIELD_NUMBER = 2;
    private java.util.List<edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB> timelineEvent_;
    public java.util.List<edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB> getTimelineEventList() {
      return timelineEvent_;
    }
    public java.util.List<? extends edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder> 
        getTimelineEventOrBuilderList() {
      return timelineEvent_;
    }
    public int getTimelineEventCount() {
      return timelineEvent_.size();
    }
    public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB getTimelineEvent(int index) {
      return timelineEvent_.get(index);
    }
    public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder getTimelineEventOrBuilder(
        int index) {
      return timelineEvent_.get(index);
    }
    
    // optional string file_type = 3;
    public static final int FILE_TYPE_FIELD_NUMBER = 3;
    private java.lang.Object fileType_;
    public boolean hasFileType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getFileType() {
      java.lang.Object ref = fileType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fileType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFileTypeBytes() {
      java.lang.Object ref = fileType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fileType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      fileName_ = "";
      timelineEvent_ = java.util.Collections.emptyList();
      fileType_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFileNameBytes());
      }
      for (int i = 0; i < timelineEvent_.size(); i++) {
        output.writeMessage(2, timelineEvent_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getFileTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFileNameBytes());
      }
      for (int i = 0; i < timelineEvent_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, timelineEvent_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFileTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.internal_static_WeTimelineFile_PB_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.internal_static_WeTimelineFile_PB_fieldAccessorTable;
      }
      
      // Construct using edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTimelineEventFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (timelineEventBuilder_ == null) {
          timelineEvent_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          timelineEventBuilder_.clear();
        }
        fileType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB.getDescriptor();
      }
      
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB getDefaultInstanceForType() {
        return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB.getDefaultInstance();
      }
      
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB build() {
        edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB buildPartial() {
        edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB result = new edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fileName_ = fileName_;
        if (timelineEventBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            timelineEvent_ = java.util.Collections.unmodifiableList(timelineEvent_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.timelineEvent_ = timelineEvent_;
        } else {
          result.timelineEvent_ = timelineEventBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fileType_ = fileType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB) {
          return mergeFrom((edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB other) {
        if (other == edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB.getDefaultInstance()) return this;
        if (other.hasFileName()) {
          setFileName(other.getFileName());
        }
        if (timelineEventBuilder_ == null) {
          if (!other.timelineEvent_.isEmpty()) {
            if (timelineEvent_.isEmpty()) {
              timelineEvent_ = other.timelineEvent_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTimelineEventIsMutable();
              timelineEvent_.addAll(other.timelineEvent_);
            }
            onChanged();
          }
        } else {
          if (!other.timelineEvent_.isEmpty()) {
            if (timelineEventBuilder_.isEmpty()) {
              timelineEventBuilder_.dispose();
              timelineEventBuilder_ = null;
              timelineEvent_ = other.timelineEvent_;
              bitField0_ = (bitField0_ & ~0x00000002);
              timelineEventBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTimelineEventFieldBuilder() : null;
            } else {
              timelineEventBuilder_.addAllMessages(other.timelineEvent_);
            }
          }
        }
        if (other.hasFileType()) {
          setFileType(other.getFileType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fileName_ = input.readBytes();
              break;
            }
            case 18: {
              edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder subBuilder = edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTimelineEvent(subBuilder.buildPartial());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              fileType_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string file_name = 1;
      private java.lang.Object fileName_ = "";
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFileName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileName_ = value;
        onChanged();
        return this;
      }
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      void setFileName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        fileName_ = value;
        onChanged();
      }
      
      // repeated .TimelineEvent_PB timeline_event = 2;
      private java.util.List<edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB> timelineEvent_ =
        java.util.Collections.emptyList();
      private void ensureTimelineEventIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          timelineEvent_ = new java.util.ArrayList<edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB>(timelineEvent_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder> timelineEventBuilder_;
      
      public java.util.List<edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB> getTimelineEventList() {
        if (timelineEventBuilder_ == null) {
          return java.util.Collections.unmodifiableList(timelineEvent_);
        } else {
          return timelineEventBuilder_.getMessageList();
        }
      }
      public int getTimelineEventCount() {
        if (timelineEventBuilder_ == null) {
          return timelineEvent_.size();
        } else {
          return timelineEventBuilder_.getCount();
        }
      }
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB getTimelineEvent(int index) {
        if (timelineEventBuilder_ == null) {
          return timelineEvent_.get(index);
        } else {
          return timelineEventBuilder_.getMessage(index);
        }
      }
      public Builder setTimelineEvent(
          int index, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB value) {
        if (timelineEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimelineEventIsMutable();
          timelineEvent_.set(index, value);
          onChanged();
        } else {
          timelineEventBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTimelineEvent(
          int index, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder builderForValue) {
        if (timelineEventBuilder_ == null) {
          ensureTimelineEventIsMutable();
          timelineEvent_.set(index, builderForValue.build());
          onChanged();
        } else {
          timelineEventBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTimelineEvent(edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB value) {
        if (timelineEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimelineEventIsMutable();
          timelineEvent_.add(value);
          onChanged();
        } else {
          timelineEventBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTimelineEvent(
          int index, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB value) {
        if (timelineEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimelineEventIsMutable();
          timelineEvent_.add(index, value);
          onChanged();
        } else {
          timelineEventBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTimelineEvent(
          edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder builderForValue) {
        if (timelineEventBuilder_ == null) {
          ensureTimelineEventIsMutable();
          timelineEvent_.add(builderForValue.build());
          onChanged();
        } else {
          timelineEventBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTimelineEvent(
          int index, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder builderForValue) {
        if (timelineEventBuilder_ == null) {
          ensureTimelineEventIsMutable();
          timelineEvent_.add(index, builderForValue.build());
          onChanged();
        } else {
          timelineEventBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTimelineEvent(
          java.lang.Iterable<? extends edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB> values) {
        if (timelineEventBuilder_ == null) {
          ensureTimelineEventIsMutable();
          super.addAll(values, timelineEvent_);
          onChanged();
        } else {
          timelineEventBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTimelineEvent() {
        if (timelineEventBuilder_ == null) {
          timelineEvent_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          timelineEventBuilder_.clear();
        }
        return this;
      }
      public Builder removeTimelineEvent(int index) {
        if (timelineEventBuilder_ == null) {
          ensureTimelineEventIsMutable();
          timelineEvent_.remove(index);
          onChanged();
        } else {
          timelineEventBuilder_.remove(index);
        }
        return this;
      }
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder getTimelineEventBuilder(
          int index) {
        return getTimelineEventFieldBuilder().getBuilder(index);
      }
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder getTimelineEventOrBuilder(
          int index) {
        if (timelineEventBuilder_ == null) {
          return timelineEvent_.get(index);  } else {
          return timelineEventBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder> 
           getTimelineEventOrBuilderList() {
        if (timelineEventBuilder_ != null) {
          return timelineEventBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(timelineEvent_);
        }
      }
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder addTimelineEventBuilder() {
        return getTimelineEventFieldBuilder().addBuilder(
            edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.getDefaultInstance());
      }
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder addTimelineEventBuilder(
          int index) {
        return getTimelineEventFieldBuilder().addBuilder(
            index, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.getDefaultInstance());
      }
      public java.util.List<edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder> 
           getTimelineEventBuilderList() {
        return getTimelineEventFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder> 
          getTimelineEventFieldBuilder() {
        if (timelineEventBuilder_ == null) {
          timelineEventBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder, edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder>(
                  timelineEvent_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          timelineEvent_ = null;
        }
        return timelineEventBuilder_;
      }
      
      // optional string file_type = 3;
      private java.lang.Object fileType_ = "";
      public boolean hasFileType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getFileType() {
        java.lang.Object ref = fileType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fileType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFileType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fileType_ = value;
        onChanged();
        return this;
      }
      public Builder clearFileType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fileType_ = getDefaultInstance().getFileType();
        onChanged();
        return this;
      }
      void setFileType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        fileType_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:WeTimelineFile_PB)
    }
    
    static {
      defaultInstance = new WeTimelineFile_PB(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:WeTimelineFile_PB)
  }
  
  public interface TimelineEvent_PBOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string id = 1;
    boolean hasId();
    String getId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional string description = 3;
    boolean hasDescription();
    String getDescription();
    
    // optional string date_time = 4;
    boolean hasDateTime();
    String getDateTime();
  }
  public static final class TimelineEvent_PB extends
      com.google.protobuf.GeneratedMessage
      implements TimelineEvent_PBOrBuilder {
    // Use TimelineEvent_PB.newBuilder() to construct.
    private TimelineEvent_PB(Builder builder) {
      super(builder);
    }
    private TimelineEvent_PB(boolean noInit) {}
    
    private static final TimelineEvent_PB defaultInstance;
    public static TimelineEvent_PB getDefaultInstance() {
      return defaultInstance;
    }
    
    public TimelineEvent_PB getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.internal_static_TimelineEvent_PB_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.internal_static_TimelineEvent_PB_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string date_time = 4;
    public static final int DATE_TIME_FIELD_NUMBER = 4;
    private java.lang.Object dateTime_;
    public boolean hasDateTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getDateTime() {
      java.lang.Object ref = dateTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          dateTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDateTimeBytes() {
      java.lang.Object ref = dateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        dateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = "";
      name_ = "";
      description_ = "";
      dateTime_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDateTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDateTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.internal_static_TimelineEvent_PB_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.internal_static_TimelineEvent_PB_fieldAccessorTable;
      }
      
      // Construct using edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        dateTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.getDescriptor();
      }
      
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB getDefaultInstanceForType() {
        return edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.getDefaultInstance();
      }
      
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB build() {
        edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB buildPartial() {
        edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB result = new edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dateTime_ = dateTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB) {
          return mergeFrom((edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB other) {
        if (other == edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasDateTime()) {
          setDateTime(other.getDateTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              dateTime_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string description = 3;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
      }
      
      // optional string date_time = 4;
      private java.lang.Object dateTime_ = "";
      public boolean hasDateTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getDateTime() {
        java.lang.Object ref = dateTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          dateTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDateTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dateTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearDateTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dateTime_ = getDefaultInstance().getDateTime();
        onChanged();
        return this;
      }
      void setDateTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        dateTime_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:TimelineEvent_PB)
    }
    
    static {
      defaultInstance = new TimelineEvent_PB(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:TimelineEvent_PB)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_WeTimelineEvent_PB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_WeTimelineEvent_PB_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_WeTimelineFile_PB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_WeTimelineFile_PB_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TimelineEvent_PB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TimelineEvent_PB_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)WeTimeline/WeTimelineProtocolBuffer.pr" +
      "oto\"\263\002\n\022WeTimelineEvent_PB\0223\n\013action_typ" +
      "e\030\001 \001(\0162\036.WeTimelineEvent_PB.actionType\022" +
      "1\n\nevent_type\030\002 \001(\0162\035.WeTimelineEvent_PB" +
      ".eventType\022)\n\016timeline_event\030\003 \001(\0132\021.Tim" +
      "elineEvent_PB\022\017\n\007user_id\030\004 \001(\t\">\n\naction" +
      "Type\022\016\n\nNEW_ACTION\020\001\022\017\n\013UNDO_ACTION\020\002\022\017\n" +
      "\013REDO_ACTION\020\003\"9\n\teventType\022\014\n\010ADD_ITEM\020" +
      "\001\022\r\n\tEDIT_ITEM\020\002\022\017\n\013DELETE_ITEM\020\003\"d\n\021WeT" +
      "imelineFile_PB\022\021\n\tfile_name\030\001 \001(\t\022)\n\016tim",
      "eline_event\030\002 \003(\0132\021.TimelineEvent_PB\022\021\n\t" +
      "file_type\030\003 \001(\t\"T\n\020TimelineEvent_PB\022\n\n\002i" +
      "d\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 \001" +
      "(\t\022\021\n\tdate_time\030\004 \001(\tB&\n$edu.umich.imlc." +
      "mydesk.app.wetimeline"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_WeTimelineEvent_PB_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_WeTimelineEvent_PB_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_WeTimelineEvent_PB_descriptor,
              new java.lang.String[] { "ActionType", "EventType", "TimelineEvent", "UserId", },
              edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.class,
              edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineEvent_PB.Builder.class);
          internal_static_WeTimelineFile_PB_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_WeTimelineFile_PB_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_WeTimelineFile_PB_descriptor,
              new java.lang.String[] { "FileName", "TimelineEvent", "FileType", },
              edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB.class,
              edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.WeTimelineFile_PB.Builder.class);
          internal_static_TimelineEvent_PB_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_TimelineEvent_PB_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TimelineEvent_PB_descriptor,
              new java.lang.String[] { "Id", "Name", "Description", "DateTime", },
              edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.class,
              edu.umich.imlc.mydesk.app.wetimeline.WeTimelineProtocolBuffer.TimelineEvent_PB.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
